use adlister_db;

insert into users (username, email, password) values ('colkowicz0', 'jmingardo0@scribd.com', '2Uc8GJWsd0ed');
insert into users (username, email, password) values ('bebunoluwa1', 'pcarillo1@npr.org', 'xoZOPZk');
insert into users (username, email, password) values ('ojuarez2', 'ecomini2@google.ru', 'hHAseGk7zSvA');
insert into users (username, email, password) values ('rchesher3', 'etommasetti3@prlog.org', 'uPfHRjleuaGC');
insert into users (username, email, password) values ('mmonini4', 'ctournie4@dropbox.com', 'sKolFYSo63');
insert into users (username, email, password) values ('gdenne5', 'nloveman5@last.fm', 'I7KOZ55');
insert into users (username, email, password) values ('ysayes6', 'rthumnel6@wufoo.com', 'yJrg4s738');
insert into users (username, email, password) values ('bwalby7', 'cshortt7@weibo.com', 'ziM78FrIW');
insert into users (username, email, password) values ('ailden8', 'ewillden8@vimeo.com', 'KGUQnf5b');
insert into users (username, email, password) values ('jjeary9', 'jpattington9@shutterfly.com', '9pbhJLSMYI4');
insert into users (username, email, password) values ('abaxa', 'cmaliffea@histats.com', 'hCwP03feb');
insert into users (username, email, password) values ('dpavlasekb', 'bcheeneyb@blogtalkradio.com', 'eg4xXT8C');
insert into users (username, email, password) values ('gdesmondc', 'cszymanskic@hexun.com', '51VEkIGu5');
insert into users (username, email, password) values ('borrind', 'slamplughd@weather.com', 'WC8up1mI');
insert into users (username, email, password) values ('bbjerkane', 'hjirane@harvard.edu', 'Dny4asziPX2R');
insert into users (username, email, password) values ('dmaragesf', 'ffrancellof@twitpic.com', '6kWPpu4');
insert into users (username, email, password) values ('qleghg', 'rclearg@theglobeandmail.com', '9vymXc');
insert into users (username, email, password) values ('iradbournh', 'drenackownah@java.com', 'CllsMDxYk');
insert into users (username, email, password) values ('bblaineyi', 'rpeseki@4shared.com', 'nWIXq0nhP');
insert into users (username, email, password) values ('ctesdalej', 'nnazairj@uol.com.br', 'wN2Q2gRcaS4L');
insert into users (username, email, password) values ('cthomasonk', 'bschulzek@oracle.com', 'E2BbXsK');
insert into users (username, email, password) values ('sandrollil', 'mhamsherl@booking.com', 'vNbkfsiIGyW7');
insert into users (username, email, password) values ('cpedraccim', 'ddinckem@kickstarter.com', 'PjSPCuAs');
insert into users (username, email, password) values ('gtappinn', 'pgardnern@go.com', 'jMKURRakHBS');
insert into users (username, email, password) values ('tgocho', 'mkonnekeo@51.la', 'vf2F7J');
insert into users (username, email, password) values ('mhowsp', 'bdyep@toplist.cz', 'jJu4Gb');
insert into users (username, email, password) values ('mantonowiczq', 'rricardonq@slate.com', 'j1k4m7qF');
insert into users (username, email, password) values ('lpilbeamr', 'ischimekr@noaa.gov', 'WFPfUC');
insert into users (username, email, password) values ('jfildess', 'wraffons@e-recht24.de', 'zbPjMRWUmE');
insert into users (username, email, password) values ('mwaldront', 'tmacgheet@cdbaby.com', 'PK7AM1ay1');
insert into users (username, email, password) values ('gtuveyu', 'bturvieu@bizjournals.com', 'nNxNqG2S');
insert into users (username, email, password) values ('jbehningv', 'lparkenv@state.tx.us', 'lEeivuXyis');
insert into users (username, email, password) values ('vcontiw', 'kmcquirterw@macromedia.com', '8SqjTNq');
insert into users (username, email, password) values ('ffrancecionex', 'kcasox@histats.com', 'CYxV4vyQq8q');
insert into users (username, email, password) values ('rnixony', 'ttolletty@technorati.com', 'B86rwP');
insert into users (username, email, password) values ('jcheesmanz', 'aglennardz@booking.com', 'E1crrkk');
insert into users (username, email, password) values ('wguslon10', 'lpock10@salon.com', '3MT5KJEo');
insert into users (username, email, password) values ('cbotte11', 'dwylam11@archive.org', 'SuVptYdWPv');
insert into users (username, email, password) values ('fpowder12', 'spretti12@furl.net', 'hre4L2oBx5');
insert into users (username, email, password) values ('arome13', 'slilywhite13@purevolume.com', 'sK3n6NQIIF');
insert into users (username, email, password) values ('lmcsweeney14', 'ecossons14@imgur.com', 'p0Lysi');
insert into users (username, email, password) values ('imeece15', 'okennler15@latimes.com', 'HE3TIElhi');
insert into users (username, email, password) values ('stourville16', 'hfurminger16@japanpost.jp', '3fikycFcMPb');
insert into users (username, email, password) values ('dsprigings17', 'rswatman17@seattletimes.com', 'QAOvFXa');
insert into users (username, email, password) values ('frevan18', 'odelloyd18@utexas.edu', 'iHJZ84b');
insert into users (username, email, password) values ('cburnip19', 'memes19@alibaba.com', '5tulwXC');
insert into users (username, email, password) values ('cranald1a', 'lriggoll1a@ustream.tv', 'V47zkiCR');
insert into users (username, email, password) values ('jrozenbaum1b', 'ppendock1b@latimes.com', 'vI1G5Wb3StZj');
insert into users (username, email, password) values ('htaverner1c', 'cpalphreyman1c@fc2.com', 'lsoIXDa');
insert into users (username, email, password) values ('crenfield1d', 'lgraver1d@loc.gov', 'hqtIMA');

insert into ads (user_id, title, description) values (47, 'Ford', 'Explorer');
insert into ads (user_id, title, description) values (3, 'Saab', '900');
insert into ads (user_id, title, description) values (8, 'Dodge', 'Intrepid');
insert into ads (user_id, title, description) values (21, 'Holden', 'Monaro');
insert into ads (user_id, title, description) values (11, 'Cadillac', 'CTS-V');
insert into ads (user_id, title, description) values (9, 'Subaru', 'Impreza');
insert into ads (user_id, title, description) values (37, 'Cadillac', 'Fleetwood');
insert into ads (user_id, title, description) values (24, 'Subaru', 'Impreza');
insert into ads (user_id, title, description) values (32, 'Dodge', 'Colt');
insert into ads (user_id, title, description) values (14, 'BMW', 'X5');
insert into ads (user_id, title, description) values (30, 'Chrysler', 'Aspen');
insert into ads (user_id, title, description) values (1, 'Lexus', 'RX Hybrid');
insert into ads (user_id, title, description) values (27, 'Dodge', 'D350 Club');
insert into ads (user_id, title, description) values (18, 'Lincoln', 'Continental');
insert into ads (user_id, title, description) values (10, 'BMW', 'X5');
insert into ads (user_id, title, description) values (28, 'Jeep', 'Grand Cherokee');
insert into ads (user_id, title, description) values (14, 'Ford', 'Probe');
insert into ads (user_id, title, description) values (33, 'Mazda', '929');
insert into ads (user_id, title, description) values (20, 'Chrysler', 'Sebring');
insert into ads (user_id, title, description) values (15, 'GMC', 'Savana');
insert into ads (user_id, title, description) values (11, 'Mercury', 'Cougar');
insert into ads (user_id, title, description) values (28, 'Acura', 'CL');
insert into ads (user_id, title, description) values (31, 'Volkswagen', 'rio');
insert into ads (user_id, title, description) values (44, 'Dodge', 'Avenger');
insert into ads (user_id, title, description) values (1, 'Cadillac', 'DeVille');
insert into ads (user_id, title, description) values (22, 'Chevrolet', 'S10');
insert into ads (user_id, title, description) values (7, 'Volkswagen', 'Rabbit');
insert into ads (user_id, title, description) values (46, 'Ford', 'F-Series');
insert into ads (user_id, title, description) values (8, 'Ford', 'Explorer Sport Trac');
insert into ads (user_id, title, description) values (7, 'Toyota', 'Previa');
insert into ads (user_id, title, description) values (2, 'Mercedes-Benz', 'CLS-Class');
insert into ads (user_id, title, description) values (40, 'Mercedes-Benz', 'G-Class');
insert into ads (user_id, title, description) values (15, 'Toyota', 'Tacoma');
insert into ads (user_id, title, description) values (6, 'Ford', 'Taurus');
insert into ads (user_id, title, description) values (30, 'Lexus', 'IS-F');
insert into ads (user_id, title, description) values (33, 'Panoz', 'Esperante');
insert into ads (user_id, title, description) values (18, 'Lexus', 'ES');
insert into ads (user_id, title, description) values (41, 'Ford', 'Thunderbird');
insert into ads (user_id, title, description) values (35, 'Cadillac', 'Allante');
insert into ads (user_id, title, description) values (45, 'Ford', 'Crown Victoria');
insert into ads (user_id, title, description) values (48, 'Aston Martin', 'Vantage');
insert into ads (user_id, title, description) values (47, 'Porsche', '911');
insert into ads (user_id, title, description) values (21, 'Audi', 'TT');
insert into ads (user_id, title, description) values (39, 'Ford', 'Taurus');
insert into ads (user_id, title, description) values (50, 'Volkswagen', 'GTI');
insert into ads (user_id, title, description) values (24, 'GMC', 'Savana 3500');
insert into ads (user_id, title, description) values (29, 'Plymouth', 'Voyager');
insert into ads (user_id, title, description) values (48, 'Ford', 'Ranger');
insert into ads (user_id, title, description) values (27, 'Mazda', 'Mazda3');
insert into ads (user_id, title, description) values (38, 'Chevrolet', 'Camaro');
